# eda-backend/docker-compose.yml
# Docker Compose configuration for your FastAPI backend.

services:
  backend:
    # Build the Docker image using the Dockerfile in the current directory.
    # This will use the eda-backend/Dockerfile you already have.
    build: .
    
    # Map port 8000 on your host machine to port 8000 inside the container.
    # This allows you to access the FastAPI app via http://localhost:8000.
    ports:
      - "8000:8000"
    
    # Load environment variables from your .env file.
    # This is crucial for your database credentials, API keys, etc.
    env_file:
      - ./.env
    
    # Mount the current directory into the container's /app directory.
    # This enables hot-reloading during development, so changes to your code
    # on your host machine are reflected inside the container without rebuilding.
    volumes:
      - .:/app
    
    # Command to run the application when the container starts.
    # IMPORTANT CHANGE: Point to app.main:app because main.py is inside the 'app' directory.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
    # Restart policy:
    # "unless-stopped" means the container will restart automatically unless explicitly stopped.
    # This is good for development. For production, you might use "always" or "on-failure".
    restart: unless-stopped
    
    # Optional: Assign a name to the container for easier identification.
    container_name: silicon-backend